language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"

matrix:
  allow_failures:

# setup links to submodules
before_install:
  - npm install -g npm@1.4.23
  - npm run-script setup
  - npm install

script:
  - npm test