language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"


matrix:
  allow_failures:
    - node_js: "0.11"

# setup links to submodules
before_install:
  - npm install -g npm@1.4.9
  - npm run-script setup
