language: node_js
sudo: false
node_js:
  - "6"
  - "4"

matrix:
  allow_failures:
    - node_js: "4"

# setup links to submodules
before_install:
  - npm install -g npm
  - npm install
  #- cd ..
  #- git clone https://github.com/azure/azure-xplat-cli.git
  #- cd azure-xplat-cli
  #- git checkout dev
  #- node scripts/link-to-sdk.js
  #- npm install

script:
  #- cd ../azure-sdk-for-node
  - npm test
  #- cd ../azure-xplat-cli
  #- npm test
