language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"


matrix:
  allow_failures:
    - node_js: "0.11"

# setup links to submodules
before_install:
  - npm update -g npm
  - npm install
  - npm run-script setup
  - cd ..
  - git clone https://github.com/azure/azure-sdk-tools-xplat.git
  - cd azure-sdk-tools-xplat
  - node scripts/link-to-sdk.js
  - npm install
  
script:
  - cd ../azure-sdk-for-node
  - npm test
  - cd ../azure-sdk-tools-xplat
  - npm run unit
  - node bin/azure config mode arm
  - npm run unit-arm
  
